In [1]:
import cv2
import os
import numpy as np
import tensorflow as tf
import time
import sys


2022-11-24 19:57:11.200952: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hyunsookim/.conda/envs/research_env/lib/python3.7/site-packages/cv2/../../lib64:
2022-11-24 19:57:11.200986: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [66]:
class Args:
    model = 'lite-model_movenet_singlepose_lightning_tflite_int8_4.tflite'
    inp = 'standing_man.jpg'
    inp = '../woman_1.jpg'
    output = f"out_{inp}"
    output = "output.jpg"
    
_NUM_KEYPOINTS = 17

In [68]:
args = Args()

interpreter = tf.lite.Interpreter(args.model)
interpreter.allocate_tensors()
_, h, w, _ = interpreter.get_input_details()[0]['shape']
print(h, w)
orig_img = cv2.imread(args.inp)
img = cv2.resize(orig_img, (w, h))
img = np.reshape(np.array(img), (1, w, h, 3))
# img = np.float32(img)


input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
# print(input_details)
# print("-"*8)
# print(output_details)

interpreter.set_tensor(input_details[0]['index'], img)

# run model
interpreter.invoke()

outputs = interpreter.get_tensor(output_details[0]['index'])

pose = outputs[0, 0]
print(pose)
orig_h, orig_w, _ = orig_img.shape
print(orig_w, orig_h)
for i in range(0, _NUM_KEYPOINTS):
    
    cv2.circle(orig_img, (int( pose[i][1] * orig_w),
                         int(pose[i][0] * orig_h)), 1, (255, 255, 0), 5)
#     draw.ellipse(
#         xy=[
#             pose[i][1] * width - 2, pose[i][0] * height - 2,
#             pose[i][1] * width + 2, pose[i][0] * height + 2
#         ],
#         fill=(255, 0, 0))
cv2.imwrite(args.output, orig_img)

print('Done. Results saved at', args.output)



192 192
[[0.4096854  0.78659594 0.49981618]
 [0.39739484 0.80708027 0.49981618]
 [0.39329797 0.8029834  0.6350124 ]
 [0.3851043  0.77020854 0.24581125]
 [0.36462    0.77020854 0.49981618]
 [0.42607284 0.72924    0.43016967]
 [0.4014917  0.68827146 0.6350124 ]
 [0.50391304 0.6186249  0.24581125]
 [0.49981618 0.6022375  0.36462   ]
 [0.5776564  0.6309155  0.6350124 ]
 [0.5858501  0.61043125 0.29907036]
 [0.54897845 0.53259104 0.49981618]
 [0.5243973  0.5080099  0.6350124 ]
 [0.65549666 0.5735596  0.49981618]
 [0.68417466 0.4342665  0.5694627 ]
 [0.84395194 0.53259104 0.49981618]
 [0.70875573 0.22942382 0.36462   ]]
511 720
Done. Results saved at output.jpg
